### ISSUE TITLE
Change to assessments aren't reflected on Reports page without page reload.

### ISSUE THREAD

**Issue by LordFratz** [revaturelabs/caliber#756]
### Issue Description
Changes made to assessments on the Assess Batch page is not immediately reflected on the Reports page until the whole page is refreshed (i.e. pressing F5 or the reload button on your browser). If the Assess Batch page is changed before ever going to the Reports page, the changes are reflected but any changes after that when switching back to the Assess batch page aren't. This is most likely caused because of batch information not being reloaded every time the page is switched to Reports.

### Expected behavior
Changes made to assessments on the Assess Batch page are always reflected on the Reports page.

### Actual behavior (bugs)
Once the Reports page has been loaded once, changes aren't reflected on the Reports page when changing assessments on the Assess Batch page.

### Steps for replicating (bugs)
Navigate to the Reports page to initially load up the information.
Navigate to the Assess Batch page and change some grades around.
Navigate back to the reports page and see nothing has changed.
Reload the page using F5 and see that information is now correct.

### Screenshots (if applicable)
Changed from:
![image](https://user-images.githubusercontent.com/15112761/31498526-210ca6c2-af30-11e7-8037-e0cc2be7b743.png)

Changed to;
![image](https://user-images.githubusercontent.com/15112761/31498550-336e5810-af30-11e7-8877-2351c78d10c2.png)

Before reload:
![image](https://user-images.githubusercontent.com/15112761/31498633-83c5f57a-af30-11e7-9934-fc78b026711f.png)

After reload:
![image](https://user-images.githubusercontent.com/15112761/31498652-90cedb74-af30-11e7-8c74-b6e5888f3d10.png)

**Comment by pjw6193** [comment]
resolved
