### ISSUE TITLE
Search Box Performance

### ISSUE THREAD

**Issue by pjw6193** [revaturelabs/caliber#796]
### Issue Description
The Search Box on the Panel and Reports page takes long time to load if you click the down arrow without any search contents. This challenge comes from the fact that you are searching thru every single associate! Let's remove this down arrow and only populate the suggestions when the user begins to type a value. This will temporarily improve the performance of the search options.

### Screenshots (if applicable)
![search-performance](https://user-images.githubusercontent.com/20826349/32466288-6bcf8d44-c314-11e7-8ce8-94b9d31093d1.png)

**Comment by erchiggins** [comment]
Current status: trainee list is only loaded after a value is typed into the box, so there's less interference with initial page loading, but searching could be refined by not getting all trainees at once when that occurs.
